package et.edu.bdu.algo._4_hill;

import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

public class MatrixInputDialog extends javax.swing.JDialog {

    private JSpinner[][] spinnerses;
    private int[][] matrix;

    public MatrixInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
        }
        //</editor-fold>
        initComponents();
        JSpinner[][] _spinnerses = {{m00, m01, m02, m03, m04, m05, m06, m07, m08, m09}, {m10, m11, m12, m13, m14, m15, m16, m17, m18, m19}, {m20, m21, m22, m23, m24, m25, m26, m27, m28, m29}, {m30, m31, m32, m33, m34, m35, m36, m37, m38, m39}, {m40, m41, m42, m43, m44, m45, m46, m47, m48, m49}, {m50, m51, m52, m53, m54, m55, m56, m57, m58, m59}, {m60, m61, m62, m63, m64, m65, m66, m67, m68, m69}, {m70, m71, m72, m73, m74, m75, m76, m77, m78, m79}, {m80, m81, m82, m83, m84, m85, m86, m87, m88, m89}, {m90, m91, m92, m93, m94, m95, m96, m97, m98, m99}};
        spinnerses = _spinnerses;
        mStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        m = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        m00 = new javax.swing.JSpinner();
        m01 = new javax.swing.JSpinner();
        m02 = new javax.swing.JSpinner();
        m03 = new javax.swing.JSpinner();
        m04 = new javax.swing.JSpinner();
        m05 = new javax.swing.JSpinner();
        m06 = new javax.swing.JSpinner();
        m07 = new javax.swing.JSpinner();
        m08 = new javax.swing.JSpinner();
        m09 = new javax.swing.JSpinner();
        m10 = new javax.swing.JSpinner();
        m11 = new javax.swing.JSpinner();
        m12 = new javax.swing.JSpinner();
        m13 = new javax.swing.JSpinner();
        m14 = new javax.swing.JSpinner();
        m15 = new javax.swing.JSpinner();
        m16 = new javax.swing.JSpinner();
        m17 = new javax.swing.JSpinner();
        m18 = new javax.swing.JSpinner();
        m19 = new javax.swing.JSpinner();
        m20 = new javax.swing.JSpinner();
        m21 = new javax.swing.JSpinner();
        m22 = new javax.swing.JSpinner();
        m23 = new javax.swing.JSpinner();
        m24 = new javax.swing.JSpinner();
        m25 = new javax.swing.JSpinner();
        m26 = new javax.swing.JSpinner();
        m27 = new javax.swing.JSpinner();
        m28 = new javax.swing.JSpinner();
        m29 = new javax.swing.JSpinner();
        m30 = new javax.swing.JSpinner();
        m31 = new javax.swing.JSpinner();
        m32 = new javax.swing.JSpinner();
        m33 = new javax.swing.JSpinner();
        m34 = new javax.swing.JSpinner();
        m35 = new javax.swing.JSpinner();
        m36 = new javax.swing.JSpinner();
        m37 = new javax.swing.JSpinner();
        m38 = new javax.swing.JSpinner();
        m39 = new javax.swing.JSpinner();
        m40 = new javax.swing.JSpinner();
        m41 = new javax.swing.JSpinner();
        m42 = new javax.swing.JSpinner();
        m43 = new javax.swing.JSpinner();
        m44 = new javax.swing.JSpinner();
        m45 = new javax.swing.JSpinner();
        m46 = new javax.swing.JSpinner();
        m47 = new javax.swing.JSpinner();
        m48 = new javax.swing.JSpinner();
        m49 = new javax.swing.JSpinner();
        m50 = new javax.swing.JSpinner();
        m51 = new javax.swing.JSpinner();
        m52 = new javax.swing.JSpinner();
        m53 = new javax.swing.JSpinner();
        m54 = new javax.swing.JSpinner();
        m55 = new javax.swing.JSpinner();
        m56 = new javax.swing.JSpinner();
        m57 = new javax.swing.JSpinner();
        m58 = new javax.swing.JSpinner();
        m59 = new javax.swing.JSpinner();
        m60 = new javax.swing.JSpinner();
        m61 = new javax.swing.JSpinner();
        m62 = new javax.swing.JSpinner();
        m63 = new javax.swing.JSpinner();
        m64 = new javax.swing.JSpinner();
        m65 = new javax.swing.JSpinner();
        m66 = new javax.swing.JSpinner();
        m67 = new javax.swing.JSpinner();
        m68 = new javax.swing.JSpinner();
        m69 = new javax.swing.JSpinner();
        m70 = new javax.swing.JSpinner();
        m71 = new javax.swing.JSpinner();
        m72 = new javax.swing.JSpinner();
        m73 = new javax.swing.JSpinner();
        m74 = new javax.swing.JSpinner();
        m75 = new javax.swing.JSpinner();
        m76 = new javax.swing.JSpinner();
        m77 = new javax.swing.JSpinner();
        m78 = new javax.swing.JSpinner();
        m79 = new javax.swing.JSpinner();
        m80 = new javax.swing.JSpinner();
        m81 = new javax.swing.JSpinner();
        m82 = new javax.swing.JSpinner();
        m83 = new javax.swing.JSpinner();
        m84 = new javax.swing.JSpinner();
        m85 = new javax.swing.JSpinner();
        m86 = new javax.swing.JSpinner();
        m87 = new javax.swing.JSpinner();
        m88 = new javax.swing.JSpinner();
        m89 = new javax.swing.JSpinner();
        m90 = new javax.swing.JSpinner();
        m91 = new javax.swing.JSpinner();
        m92 = new javax.swing.JSpinner();
        m93 = new javax.swing.JSpinner();
        m94 = new javax.swing.JSpinner();
        m95 = new javax.swing.JSpinner();
        m96 = new javax.swing.JSpinner();
        m97 = new javax.swing.JSpinner();
        m98 = new javax.swing.JSpinner();
        m99 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hill Cipher Key");

        m.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
        m.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("M");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        m00.setMaximumSize(new java.awt.Dimension(40, 28));
        m00.setMinimumSize(new java.awt.Dimension(40, 28));
        m00.setName(""); // NOI18N
        m00.setPreferredSize(new java.awt.Dimension(40, 28));

        m01.setMaximumSize(new java.awt.Dimension(40, 28));
        m01.setMinimumSize(new java.awt.Dimension(40, 28));
        m01.setName(""); // NOI18N
        m01.setPreferredSize(new java.awt.Dimension(40, 28));

        m02.setMaximumSize(new java.awt.Dimension(40, 28));
        m02.setMinimumSize(new java.awt.Dimension(40, 28));
        m02.setName(""); // NOI18N
        m02.setPreferredSize(new java.awt.Dimension(40, 28));

        m03.setMaximumSize(new java.awt.Dimension(40, 28));
        m03.setMinimumSize(new java.awt.Dimension(40, 28));
        m03.setName(""); // NOI18N
        m03.setPreferredSize(new java.awt.Dimension(40, 28));

        m04.setMaximumSize(new java.awt.Dimension(40, 28));
        m04.setMinimumSize(new java.awt.Dimension(40, 28));
        m04.setName(""); // NOI18N
        m04.setPreferredSize(new java.awt.Dimension(40, 28));

        m05.setMaximumSize(new java.awt.Dimension(40, 28));
        m05.setMinimumSize(new java.awt.Dimension(40, 28));
        m05.setName(""); // NOI18N
        m05.setPreferredSize(new java.awt.Dimension(40, 28));

        m06.setMaximumSize(new java.awt.Dimension(40, 28));
        m06.setMinimumSize(new java.awt.Dimension(40, 28));
        m06.setName(""); // NOI18N
        m06.setPreferredSize(new java.awt.Dimension(40, 28));

        m07.setMaximumSize(new java.awt.Dimension(40, 28));
        m07.setMinimumSize(new java.awt.Dimension(40, 28));
        m07.setName(""); // NOI18N
        m07.setPreferredSize(new java.awt.Dimension(40, 28));

        m08.setMaximumSize(new java.awt.Dimension(40, 28));
        m08.setMinimumSize(new java.awt.Dimension(40, 28));
        m08.setName(""); // NOI18N
        m08.setPreferredSize(new java.awt.Dimension(40, 28));

        m09.setMaximumSize(new java.awt.Dimension(40, 28));
        m09.setMinimumSize(new java.awt.Dimension(40, 28));
        m09.setName(""); // NOI18N
        m09.setPreferredSize(new java.awt.Dimension(40, 28));

        m10.setMaximumSize(new java.awt.Dimension(40, 28));
        m10.setMinimumSize(new java.awt.Dimension(40, 28));
        m10.setName(""); // NOI18N
        m10.setPreferredSize(new java.awt.Dimension(40, 28));

        m11.setMaximumSize(new java.awt.Dimension(40, 28));
        m11.setMinimumSize(new java.awt.Dimension(40, 28));
        m11.setName(""); // NOI18N
        m11.setPreferredSize(new java.awt.Dimension(40, 28));

        m12.setMaximumSize(new java.awt.Dimension(40, 28));
        m12.setMinimumSize(new java.awt.Dimension(40, 28));
        m12.setName(""); // NOI18N
        m12.setPreferredSize(new java.awt.Dimension(40, 28));

        m13.setMaximumSize(new java.awt.Dimension(40, 28));
        m13.setMinimumSize(new java.awt.Dimension(40, 28));
        m13.setName(""); // NOI18N
        m13.setPreferredSize(new java.awt.Dimension(40, 28));

        m14.setMaximumSize(new java.awt.Dimension(40, 28));
        m14.setMinimumSize(new java.awt.Dimension(40, 28));
        m14.setName(""); // NOI18N
        m14.setPreferredSize(new java.awt.Dimension(40, 28));

        m15.setMaximumSize(new java.awt.Dimension(40, 28));
        m15.setMinimumSize(new java.awt.Dimension(40, 28));
        m15.setName(""); // NOI18N
        m15.setPreferredSize(new java.awt.Dimension(40, 28));

        m16.setMaximumSize(new java.awt.Dimension(40, 28));
        m16.setMinimumSize(new java.awt.Dimension(40, 28));
        m16.setName(""); // NOI18N
        m16.setPreferredSize(new java.awt.Dimension(40, 28));

        m17.setMaximumSize(new java.awt.Dimension(40, 28));
        m17.setMinimumSize(new java.awt.Dimension(40, 28));
        m17.setName(""); // NOI18N
        m17.setPreferredSize(new java.awt.Dimension(40, 28));

        m18.setMaximumSize(new java.awt.Dimension(40, 28));
        m18.setMinimumSize(new java.awt.Dimension(40, 28));
        m18.setName(""); // NOI18N
        m18.setPreferredSize(new java.awt.Dimension(40, 28));

        m19.setMaximumSize(new java.awt.Dimension(40, 28));
        m19.setMinimumSize(new java.awt.Dimension(40, 28));
        m19.setName(""); // NOI18N
        m19.setPreferredSize(new java.awt.Dimension(40, 28));

        m20.setMaximumSize(new java.awt.Dimension(40, 28));
        m20.setMinimumSize(new java.awt.Dimension(40, 28));
        m20.setName(""); // NOI18N
        m20.setPreferredSize(new java.awt.Dimension(40, 28));

        m21.setMaximumSize(new java.awt.Dimension(40, 28));
        m21.setMinimumSize(new java.awt.Dimension(40, 28));
        m21.setName(""); // NOI18N
        m21.setPreferredSize(new java.awt.Dimension(40, 28));

        m22.setMaximumSize(new java.awt.Dimension(40, 28));
        m22.setMinimumSize(new java.awt.Dimension(40, 28));
        m22.setName(""); // NOI18N
        m22.setPreferredSize(new java.awt.Dimension(40, 28));

        m23.setMaximumSize(new java.awt.Dimension(40, 28));
        m23.setMinimumSize(new java.awt.Dimension(40, 28));
        m23.setName(""); // NOI18N
        m23.setPreferredSize(new java.awt.Dimension(40, 28));

        m24.setMaximumSize(new java.awt.Dimension(40, 28));
        m24.setMinimumSize(new java.awt.Dimension(40, 28));
        m24.setName(""); // NOI18N
        m24.setPreferredSize(new java.awt.Dimension(40, 28));

        m25.setMaximumSize(new java.awt.Dimension(40, 28));
        m25.setMinimumSize(new java.awt.Dimension(40, 28));
        m25.setName(""); // NOI18N
        m25.setPreferredSize(new java.awt.Dimension(40, 28));

        m26.setMaximumSize(new java.awt.Dimension(40, 28));
        m26.setMinimumSize(new java.awt.Dimension(40, 28));
        m26.setName(""); // NOI18N
        m26.setPreferredSize(new java.awt.Dimension(40, 28));

        m27.setMaximumSize(new java.awt.Dimension(40, 28));
        m27.setMinimumSize(new java.awt.Dimension(40, 28));
        m27.setName(""); // NOI18N
        m27.setPreferredSize(new java.awt.Dimension(40, 28));

        m28.setMaximumSize(new java.awt.Dimension(40, 28));
        m28.setMinimumSize(new java.awt.Dimension(40, 28));
        m28.setName(""); // NOI18N
        m28.setPreferredSize(new java.awt.Dimension(40, 28));

        m29.setMaximumSize(new java.awt.Dimension(40, 28));
        m29.setMinimumSize(new java.awt.Dimension(40, 28));
        m29.setName(""); // NOI18N
        m29.setPreferredSize(new java.awt.Dimension(40, 28));

        m30.setMaximumSize(new java.awt.Dimension(40, 28));
        m30.setMinimumSize(new java.awt.Dimension(40, 28));
        m30.setName(""); // NOI18N
        m30.setPreferredSize(new java.awt.Dimension(40, 28));

        m31.setMaximumSize(new java.awt.Dimension(40, 28));
        m31.setMinimumSize(new java.awt.Dimension(40, 28));
        m31.setName(""); // NOI18N
        m31.setPreferredSize(new java.awt.Dimension(40, 28));

        m32.setMaximumSize(new java.awt.Dimension(40, 28));
        m32.setMinimumSize(new java.awt.Dimension(40, 28));
        m32.setName(""); // NOI18N
        m32.setPreferredSize(new java.awt.Dimension(40, 28));

        m33.setMaximumSize(new java.awt.Dimension(40, 28));
        m33.setMinimumSize(new java.awt.Dimension(40, 28));
        m33.setName(""); // NOI18N
        m33.setPreferredSize(new java.awt.Dimension(40, 28));

        m34.setMaximumSize(new java.awt.Dimension(40, 28));
        m34.setMinimumSize(new java.awt.Dimension(40, 28));
        m34.setName(""); // NOI18N
        m34.setPreferredSize(new java.awt.Dimension(40, 28));

        m35.setMaximumSize(new java.awt.Dimension(40, 28));
        m35.setMinimumSize(new java.awt.Dimension(40, 28));
        m35.setName(""); // NOI18N
        m35.setPreferredSize(new java.awt.Dimension(40, 28));

        m36.setMaximumSize(new java.awt.Dimension(40, 28));
        m36.setMinimumSize(new java.awt.Dimension(40, 28));
        m36.setName(""); // NOI18N
        m36.setPreferredSize(new java.awt.Dimension(40, 28));

        m37.setMaximumSize(new java.awt.Dimension(40, 28));
        m37.setMinimumSize(new java.awt.Dimension(40, 28));
        m37.setName(""); // NOI18N
        m37.setPreferredSize(new java.awt.Dimension(40, 28));

        m38.setMaximumSize(new java.awt.Dimension(40, 28));
        m38.setMinimumSize(new java.awt.Dimension(40, 28));
        m38.setName(""); // NOI18N
        m38.setPreferredSize(new java.awt.Dimension(40, 28));

        m39.setMaximumSize(new java.awt.Dimension(40, 28));
        m39.setMinimumSize(new java.awt.Dimension(40, 28));
        m39.setName(""); // NOI18N
        m39.setPreferredSize(new java.awt.Dimension(40, 28));

        m40.setMaximumSize(new java.awt.Dimension(40, 28));
        m40.setMinimumSize(new java.awt.Dimension(40, 28));
        m40.setName(""); // NOI18N
        m40.setPreferredSize(new java.awt.Dimension(40, 28));

        m41.setMaximumSize(new java.awt.Dimension(40, 28));
        m41.setMinimumSize(new java.awt.Dimension(40, 28));
        m41.setName(""); // NOI18N
        m41.setPreferredSize(new java.awt.Dimension(40, 28));

        m42.setMaximumSize(new java.awt.Dimension(40, 28));
        m42.setMinimumSize(new java.awt.Dimension(40, 28));
        m42.setName(""); // NOI18N
        m42.setPreferredSize(new java.awt.Dimension(40, 28));

        m43.setMaximumSize(new java.awt.Dimension(40, 28));
        m43.setMinimumSize(new java.awt.Dimension(40, 28));
        m43.setName(""); // NOI18N
        m43.setPreferredSize(new java.awt.Dimension(40, 28));

        m44.setMaximumSize(new java.awt.Dimension(40, 28));
        m44.setMinimumSize(new java.awt.Dimension(40, 28));
        m44.setName(""); // NOI18N
        m44.setPreferredSize(new java.awt.Dimension(40, 28));

        m45.setMaximumSize(new java.awt.Dimension(40, 28));
        m45.setMinimumSize(new java.awt.Dimension(40, 28));
        m45.setName(""); // NOI18N
        m45.setPreferredSize(new java.awt.Dimension(40, 28));

        m46.setMaximumSize(new java.awt.Dimension(40, 28));
        m46.setMinimumSize(new java.awt.Dimension(40, 28));
        m46.setName(""); // NOI18N
        m46.setPreferredSize(new java.awt.Dimension(40, 28));

        m47.setMaximumSize(new java.awt.Dimension(40, 28));
        m47.setMinimumSize(new java.awt.Dimension(40, 28));
        m47.setName(""); // NOI18N
        m47.setPreferredSize(new java.awt.Dimension(40, 28));

        m48.setMaximumSize(new java.awt.Dimension(40, 28));
        m48.setMinimumSize(new java.awt.Dimension(40, 28));
        m48.setName(""); // NOI18N
        m48.setPreferredSize(new java.awt.Dimension(40, 28));

        m49.setMaximumSize(new java.awt.Dimension(40, 28));
        m49.setMinimumSize(new java.awt.Dimension(40, 28));
        m49.setName(""); // NOI18N
        m49.setPreferredSize(new java.awt.Dimension(40, 28));

        m50.setMaximumSize(new java.awt.Dimension(40, 28));
        m50.setMinimumSize(new java.awt.Dimension(40, 28));
        m50.setName(""); // NOI18N
        m50.setPreferredSize(new java.awt.Dimension(40, 28));

        m51.setMaximumSize(new java.awt.Dimension(40, 28));
        m51.setMinimumSize(new java.awt.Dimension(40, 28));
        m51.setName(""); // NOI18N
        m51.setPreferredSize(new java.awt.Dimension(40, 28));

        m52.setMaximumSize(new java.awt.Dimension(40, 28));
        m52.setMinimumSize(new java.awt.Dimension(40, 28));
        m52.setName(""); // NOI18N
        m52.setPreferredSize(new java.awt.Dimension(40, 28));

        m53.setMaximumSize(new java.awt.Dimension(40, 28));
        m53.setMinimumSize(new java.awt.Dimension(40, 28));
        m53.setName(""); // NOI18N
        m53.setPreferredSize(new java.awt.Dimension(40, 28));

        m54.setMaximumSize(new java.awt.Dimension(40, 28));
        m54.setMinimumSize(new java.awt.Dimension(40, 28));
        m54.setName(""); // NOI18N
        m54.setPreferredSize(new java.awt.Dimension(40, 28));

        m55.setMaximumSize(new java.awt.Dimension(40, 28));
        m55.setMinimumSize(new java.awt.Dimension(40, 28));
        m55.setName(""); // NOI18N
        m55.setPreferredSize(new java.awt.Dimension(40, 28));

        m56.setMaximumSize(new java.awt.Dimension(40, 28));
        m56.setMinimumSize(new java.awt.Dimension(40, 28));
        m56.setName(""); // NOI18N
        m56.setPreferredSize(new java.awt.Dimension(40, 28));

        m57.setMaximumSize(new java.awt.Dimension(40, 28));
        m57.setMinimumSize(new java.awt.Dimension(40, 28));
        m57.setName(""); // NOI18N
        m57.setPreferredSize(new java.awt.Dimension(40, 28));

        m58.setMaximumSize(new java.awt.Dimension(40, 28));
        m58.setMinimumSize(new java.awt.Dimension(40, 28));
        m58.setName(""); // NOI18N
        m58.setPreferredSize(new java.awt.Dimension(40, 28));

        m59.setMaximumSize(new java.awt.Dimension(40, 28));
        m59.setMinimumSize(new java.awt.Dimension(40, 28));
        m59.setName(""); // NOI18N
        m59.setPreferredSize(new java.awt.Dimension(40, 28));

        m60.setMaximumSize(new java.awt.Dimension(40, 28));
        m60.setMinimumSize(new java.awt.Dimension(40, 28));
        m60.setName(""); // NOI18N
        m60.setPreferredSize(new java.awt.Dimension(40, 28));

        m61.setMaximumSize(new java.awt.Dimension(40, 28));
        m61.setMinimumSize(new java.awt.Dimension(40, 28));
        m61.setName(""); // NOI18N
        m61.setPreferredSize(new java.awt.Dimension(40, 28));

        m62.setMaximumSize(new java.awt.Dimension(40, 28));
        m62.setMinimumSize(new java.awt.Dimension(40, 28));
        m62.setName(""); // NOI18N
        m62.setPreferredSize(new java.awt.Dimension(40, 28));

        m63.setMaximumSize(new java.awt.Dimension(40, 28));
        m63.setMinimumSize(new java.awt.Dimension(40, 28));
        m63.setName(""); // NOI18N
        m63.setPreferredSize(new java.awt.Dimension(40, 28));

        m64.setMaximumSize(new java.awt.Dimension(40, 28));
        m64.setMinimumSize(new java.awt.Dimension(40, 28));
        m64.setName(""); // NOI18N
        m64.setPreferredSize(new java.awt.Dimension(40, 28));

        m65.setMaximumSize(new java.awt.Dimension(40, 28));
        m65.setMinimumSize(new java.awt.Dimension(40, 28));
        m65.setName(""); // NOI18N
        m65.setPreferredSize(new java.awt.Dimension(40, 28));

        m66.setMaximumSize(new java.awt.Dimension(40, 28));
        m66.setMinimumSize(new java.awt.Dimension(40, 28));
        m66.setName(""); // NOI18N
        m66.setPreferredSize(new java.awt.Dimension(40, 28));

        m67.setMaximumSize(new java.awt.Dimension(40, 28));
        m67.setMinimumSize(new java.awt.Dimension(40, 28));
        m67.setName(""); // NOI18N
        m67.setPreferredSize(new java.awt.Dimension(40, 28));

        m68.setMaximumSize(new java.awt.Dimension(40, 28));
        m68.setMinimumSize(new java.awt.Dimension(40, 28));
        m68.setName(""); // NOI18N
        m68.setPreferredSize(new java.awt.Dimension(40, 28));

        m69.setMaximumSize(new java.awt.Dimension(40, 28));
        m69.setMinimumSize(new java.awt.Dimension(40, 28));
        m69.setName(""); // NOI18N
        m69.setPreferredSize(new java.awt.Dimension(40, 28));

        m70.setMaximumSize(new java.awt.Dimension(40, 28));
        m70.setMinimumSize(new java.awt.Dimension(40, 28));
        m70.setName(""); // NOI18N
        m70.setPreferredSize(new java.awt.Dimension(40, 28));

        m71.setMaximumSize(new java.awt.Dimension(40, 28));
        m71.setMinimumSize(new java.awt.Dimension(40, 28));
        m71.setName(""); // NOI18N
        m71.setPreferredSize(new java.awt.Dimension(40, 28));

        m72.setMaximumSize(new java.awt.Dimension(40, 28));
        m72.setMinimumSize(new java.awt.Dimension(40, 28));
        m72.setName(""); // NOI18N
        m72.setPreferredSize(new java.awt.Dimension(40, 28));

        m73.setMaximumSize(new java.awt.Dimension(40, 28));
        m73.setMinimumSize(new java.awt.Dimension(40, 28));
        m73.setName(""); // NOI18N
        m73.setPreferredSize(new java.awt.Dimension(40, 28));

        m74.setMaximumSize(new java.awt.Dimension(40, 28));
        m74.setMinimumSize(new java.awt.Dimension(40, 28));
        m74.setName(""); // NOI18N
        m74.setPreferredSize(new java.awt.Dimension(40, 28));

        m75.setMaximumSize(new java.awt.Dimension(40, 28));
        m75.setMinimumSize(new java.awt.Dimension(40, 28));
        m75.setName(""); // NOI18N
        m75.setPreferredSize(new java.awt.Dimension(40, 28));

        m76.setMaximumSize(new java.awt.Dimension(40, 28));
        m76.setMinimumSize(new java.awt.Dimension(40, 28));
        m76.setName(""); // NOI18N
        m76.setPreferredSize(new java.awt.Dimension(40, 28));

        m77.setMaximumSize(new java.awt.Dimension(40, 28));
        m77.setMinimumSize(new java.awt.Dimension(40, 28));
        m77.setName(""); // NOI18N
        m77.setPreferredSize(new java.awt.Dimension(40, 28));

        m78.setMaximumSize(new java.awt.Dimension(40, 28));
        m78.setMinimumSize(new java.awt.Dimension(40, 28));
        m78.setName(""); // NOI18N
        m78.setPreferredSize(new java.awt.Dimension(40, 28));

        m79.setMaximumSize(new java.awt.Dimension(40, 28));
        m79.setMinimumSize(new java.awt.Dimension(40, 28));
        m79.setName(""); // NOI18N
        m79.setPreferredSize(new java.awt.Dimension(40, 28));

        m80.setMaximumSize(new java.awt.Dimension(40, 28));
        m80.setMinimumSize(new java.awt.Dimension(40, 28));
        m80.setName(""); // NOI18N
        m80.setPreferredSize(new java.awt.Dimension(40, 28));

        m81.setMaximumSize(new java.awt.Dimension(40, 28));
        m81.setMinimumSize(new java.awt.Dimension(40, 28));
        m81.setName(""); // NOI18N
        m81.setPreferredSize(new java.awt.Dimension(40, 28));

        m82.setMaximumSize(new java.awt.Dimension(40, 28));
        m82.setMinimumSize(new java.awt.Dimension(40, 28));
        m82.setName(""); // NOI18N
        m82.setPreferredSize(new java.awt.Dimension(40, 28));

        m83.setMaximumSize(new java.awt.Dimension(40, 28));
        m83.setMinimumSize(new java.awt.Dimension(40, 28));
        m83.setName(""); // NOI18N
        m83.setPreferredSize(new java.awt.Dimension(40, 28));

        m84.setMaximumSize(new java.awt.Dimension(40, 28));
        m84.setMinimumSize(new java.awt.Dimension(40, 28));
        m84.setName(""); // NOI18N
        m84.setPreferredSize(new java.awt.Dimension(40, 28));

        m85.setMaximumSize(new java.awt.Dimension(40, 28));
        m85.setMinimumSize(new java.awt.Dimension(40, 28));
        m85.setName(""); // NOI18N
        m85.setPreferredSize(new java.awt.Dimension(40, 28));

        m86.setMaximumSize(new java.awt.Dimension(40, 28));
        m86.setMinimumSize(new java.awt.Dimension(40, 28));
        m86.setName(""); // NOI18N
        m86.setPreferredSize(new java.awt.Dimension(40, 28));

        m87.setMaximumSize(new java.awt.Dimension(40, 28));
        m87.setMinimumSize(new java.awt.Dimension(40, 28));
        m87.setName(""); // NOI18N
        m87.setPreferredSize(new java.awt.Dimension(40, 28));

        m88.setMaximumSize(new java.awt.Dimension(40, 28));
        m88.setMinimumSize(new java.awt.Dimension(40, 28));
        m88.setName(""); // NOI18N
        m88.setPreferredSize(new java.awt.Dimension(40, 28));

        m89.setMaximumSize(new java.awt.Dimension(40, 28));
        m89.setMinimumSize(new java.awt.Dimension(40, 28));
        m89.setName(""); // NOI18N
        m89.setPreferredSize(new java.awt.Dimension(40, 28));

        m90.setMaximumSize(new java.awt.Dimension(40, 28));
        m90.setMinimumSize(new java.awt.Dimension(40, 28));
        m90.setName(""); // NOI18N
        m90.setPreferredSize(new java.awt.Dimension(40, 28));

        m91.setMaximumSize(new java.awt.Dimension(40, 28));
        m91.setMinimumSize(new java.awt.Dimension(40, 28));
        m91.setName(""); // NOI18N
        m91.setPreferredSize(new java.awt.Dimension(40, 28));

        m92.setMaximumSize(new java.awt.Dimension(40, 28));
        m92.setMinimumSize(new java.awt.Dimension(40, 28));
        m92.setName(""); // NOI18N
        m92.setPreferredSize(new java.awt.Dimension(40, 28));

        m93.setMaximumSize(new java.awt.Dimension(40, 28));
        m93.setMinimumSize(new java.awt.Dimension(40, 28));
        m93.setName(""); // NOI18N
        m93.setPreferredSize(new java.awt.Dimension(40, 28));

        m94.setMaximumSize(new java.awt.Dimension(40, 28));
        m94.setMinimumSize(new java.awt.Dimension(40, 28));
        m94.setName(""); // NOI18N
        m94.setPreferredSize(new java.awt.Dimension(40, 28));

        m95.setMaximumSize(new java.awt.Dimension(40, 28));
        m95.setMinimumSize(new java.awt.Dimension(40, 28));
        m95.setName(""); // NOI18N
        m95.setPreferredSize(new java.awt.Dimension(40, 28));

        m96.setMaximumSize(new java.awt.Dimension(40, 28));
        m96.setMinimumSize(new java.awt.Dimension(40, 28));
        m96.setName(""); // NOI18N
        m96.setPreferredSize(new java.awt.Dimension(40, 28));

        m97.setMaximumSize(new java.awt.Dimension(40, 28));
        m97.setMinimumSize(new java.awt.Dimension(40, 28));
        m97.setName(""); // NOI18N
        m97.setPreferredSize(new java.awt.Dimension(40, 28));

        m98.setMaximumSize(new java.awt.Dimension(40, 28));
        m98.setMinimumSize(new java.awt.Dimension(40, 28));
        m98.setName(""); // NOI18N
        m98.setPreferredSize(new java.awt.Dimension(40, 28));

        m99.setMaximumSize(new java.awt.Dimension(40, 28));
        m99.setMinimumSize(new java.awt.Dimension(40, 28));
        m99.setName(""); // NOI18N
        m99.setPreferredSize(new java.awt.Dimension(40, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mStateChanged
        fillTable(((Integer) m.getModel().getValue()).intValue());
    }//GEN-LAST:event_mStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int _m = ((Integer) m.getModel().getValue()).intValue();
        matrix = new int[_m][_m];
        for (int i = 0; i < _m; i++) {
            for (int j = 0; j < _m; j++) {
                matrix[i][j] = ((Integer) spinnerses[i][j].getModel().getValue()).intValue();
            }
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //<editor-fold defaultstate="collapsed" desc=" Variables ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner m;
    private javax.swing.JSpinner m00;
    private javax.swing.JSpinner m01;
    private javax.swing.JSpinner m02;
    private javax.swing.JSpinner m03;
    private javax.swing.JSpinner m04;
    private javax.swing.JSpinner m05;
    private javax.swing.JSpinner m06;
    private javax.swing.JSpinner m07;
    private javax.swing.JSpinner m08;
    private javax.swing.JSpinner m09;
    private javax.swing.JSpinner m10;
    private javax.swing.JSpinner m11;
    private javax.swing.JSpinner m12;
    private javax.swing.JSpinner m13;
    private javax.swing.JSpinner m14;
    private javax.swing.JSpinner m15;
    private javax.swing.JSpinner m16;
    private javax.swing.JSpinner m17;
    private javax.swing.JSpinner m18;
    private javax.swing.JSpinner m19;
    private javax.swing.JSpinner m20;
    private javax.swing.JSpinner m21;
    private javax.swing.JSpinner m22;
    private javax.swing.JSpinner m23;
    private javax.swing.JSpinner m24;
    private javax.swing.JSpinner m25;
    private javax.swing.JSpinner m26;
    private javax.swing.JSpinner m27;
    private javax.swing.JSpinner m28;
    private javax.swing.JSpinner m29;
    private javax.swing.JSpinner m30;
    private javax.swing.JSpinner m31;
    private javax.swing.JSpinner m32;
    private javax.swing.JSpinner m33;
    private javax.swing.JSpinner m34;
    private javax.swing.JSpinner m35;
    private javax.swing.JSpinner m36;
    private javax.swing.JSpinner m37;
    private javax.swing.JSpinner m38;
    private javax.swing.JSpinner m39;
    private javax.swing.JSpinner m40;
    private javax.swing.JSpinner m41;
    private javax.swing.JSpinner m42;
    private javax.swing.JSpinner m43;
    private javax.swing.JSpinner m44;
    private javax.swing.JSpinner m45;
    private javax.swing.JSpinner m46;
    private javax.swing.JSpinner m47;
    private javax.swing.JSpinner m48;
    private javax.swing.JSpinner m49;
    private javax.swing.JSpinner m50;
    private javax.swing.JSpinner m51;
    private javax.swing.JSpinner m52;
    private javax.swing.JSpinner m53;
    private javax.swing.JSpinner m54;
    private javax.swing.JSpinner m55;
    private javax.swing.JSpinner m56;
    private javax.swing.JSpinner m57;
    private javax.swing.JSpinner m58;
    private javax.swing.JSpinner m59;
    private javax.swing.JSpinner m60;
    private javax.swing.JSpinner m61;
    private javax.swing.JSpinner m62;
    private javax.swing.JSpinner m63;
    private javax.swing.JSpinner m64;
    private javax.swing.JSpinner m65;
    private javax.swing.JSpinner m66;
    private javax.swing.JSpinner m67;
    private javax.swing.JSpinner m68;
    private javax.swing.JSpinner m69;
    private javax.swing.JSpinner m70;
    private javax.swing.JSpinner m71;
    private javax.swing.JSpinner m72;
    private javax.swing.JSpinner m73;
    private javax.swing.JSpinner m74;
    private javax.swing.JSpinner m75;
    private javax.swing.JSpinner m76;
    private javax.swing.JSpinner m77;
    private javax.swing.JSpinner m78;
    private javax.swing.JSpinner m79;
    private javax.swing.JSpinner m80;
    private javax.swing.JSpinner m81;
    private javax.swing.JSpinner m82;
    private javax.swing.JSpinner m83;
    private javax.swing.JSpinner m84;
    private javax.swing.JSpinner m85;
    private javax.swing.JSpinner m86;
    private javax.swing.JSpinner m87;
    private javax.swing.JSpinner m88;
    private javax.swing.JSpinner m89;
    private javax.swing.JSpinner m90;
    private javax.swing.JSpinner m91;
    private javax.swing.JSpinner m92;
    private javax.swing.JSpinner m93;
    private javax.swing.JSpinner m94;
    private javax.swing.JSpinner m95;
    private javax.swing.JSpinner m96;
    private javax.swing.JSpinner m97;
    private javax.swing.JSpinner m98;
    private javax.swing.JSpinner m99;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    private void fillTable(int m) {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                spinnerses[i][j].setModel(new SpinnerNumberModel(0, 0, 25, 1));
                if (i >= m || j >= m) {
                    spinnerses[i][j].setVisible(false);
                } else {
                    spinnerses[i][j].setVisible(true);
                }
            }
        }
    }

    public int[][] getMatrix() {
        return matrix;
    }

}
