/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samasend;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author SamAsEnd
 */
public class GUI extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement insert;
    private PreparedStatement updatePreparedStatement;
    private PreparedStatement deletePreparedStatement;
    private Statement stmt;

    public GUI(String title, Connection conn) {
        super(title);
        this.conn = conn;
        initComponents();
        try {
            insert = conn.prepareStatement("INSERT INTO `paitient` (\n"
                    + "`id` ,\n"
                    + "`pName` ,\n"
                    + "`sex` ,\n"
                    + "`desType` ,\n"
                    + "`drName`\n"
                    + ")\n"
                    + "VALUES (\n"
                    + " ? ,? ,? ,? ,? \n"
                    + ");");
            updatePreparedStatement = conn.prepareStatement("UPDATE `paitient`\n"
                    + "	SET `id`=?,`pName`=?,`sex`=?,`desType`=?,`drName`=?\n"
                    + "        	WHERE `id` = ?;");
            deletePreparedStatement = conn.prepareStatement("DELETE FROM `paitient` WHERE `id` = ?;");
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            Start.couldNotConnect(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        addPanel = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        idLable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        desType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        drName = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        sex = new javax.swing.JComboBox();
        clear = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        updatePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        updateList = new javax.swing.JList();
        id1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        updateDrName = new javax.swing.JTextField();
        updateDesType = new javax.swing.JTextField();
        updateSex = new javax.swing.JComboBox();
        updatepName = new javax.swing.JTextField();
        updateId = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deletePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        deleteList = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        searchPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        searchNameBtn = new javax.swing.JButton();
        searchPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        searchDiseaseNameTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        searchDesType = new javax.swing.JTextField();
        searchNameBtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sam As End");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Admission System");

        addPanel.setBackground(new java.awt.Color(255, 255, 255));
        addPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addPanelComponentShown(evt);
            }
        });

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id.setPreferredSize(new java.awt.Dimension(225, 28));

        idLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLable.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Paitient Name :");

        pName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pName.setPreferredSize(new java.awt.Dimension(225, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sex :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Disease Name :");

        desType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desType.setPreferredSize(new java.awt.Dimension(225, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Dr. Name :");

        drName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drName.setPreferredSize(new java.awt.Dimension(225, 28));

        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setText("Add");
        add.setPreferredSize(new java.awt.Dimension(63, 35));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        sex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.setPreferredSize(new java.awt.Dimension(63, 35));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addPanelLayout.createSequentialGroup()
                            .addComponent(idLable, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(sex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Add", addPanel);

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                viewPanelComponentShown(evt);
            }
        });

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Sex", "Disease Name", "Dr. Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("View", viewPanel);

        updatePanel.setBackground(new java.awt.Color(255, 255, 255));
        updatePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updatePanelComponentShown(evt);
            }
        });

        updateList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Select" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        updateList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        updateList.setToolTipText("Select the one u want to update");
        updateList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                updateListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(updateList);

        id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        id1.setText("ID :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Paitient Name :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Sex :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Disease Name :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Dr. Name :");

        updateDrName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateDrName.setPreferredSize(new java.awt.Dimension(225, 28));

        updateDesType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateDesType.setPreferredSize(new java.awt.Dimension(225, 28));

        updateSex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        updatepName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updatepName.setPreferredSize(new java.awt.Dimension(225, 28));

        updateId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateId.setPreferredSize(new java.awt.Dimension(225, 28));

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.setPreferredSize(new java.awt.Dimension(63, 35));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(updatePanelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateSex, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(updatePanelLayout.createSequentialGroup()
                            .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateDesType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatepName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateDrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(75, 75, 75))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(updateSex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateDesType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateDrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Update", updatePanel);

        deletePanel.setBackground(new java.awt.Color(255, 255, 255));
        deletePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deletePanelComponentShown(evt);
            }
        });

        deleteList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Select" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        deleteList.setToolTipText("Select the one u want to update");
        jScrollPane3.setViewportView(deleteList);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setPreferredSize(new java.awt.Dimension(63, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Delete", deletePanel);

        searchPanel1.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                searchPanel1ComponentShown(evt);
            }
        });

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Sex", "Disease Name", "Dr. Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(searchTable);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Search By Patien Name:");

        searchName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchName.setPreferredSize(new java.awt.Dimension(225, 28));
        searchName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchNameCaretUpdate(evt);
            }
        });

        searchNameBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchNameBtn.setText("Search");
        searchNameBtn.setPreferredSize(new java.awt.Dimension(63, 35));
        searchNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanel1Layout = new javax.swing.GroupLayout(searchPanel1);
        searchPanel1.setLayout(searchPanel1Layout);
        searchPanel1Layout.setHorizontalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        searchPanel1Layout.setVerticalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(searchNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Search By Name", searchPanel1);

        searchPanel2.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                searchPanel2ComponentShown(evt);
            }
        });

        searchDiseaseNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Sex", "Disease Name", "Dr. Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(searchDiseaseNameTable);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Search By Disease Name:");

        searchDesType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchDesType.setPreferredSize(new java.awt.Dimension(225, 28));
        searchDesType.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchDesTypeCaretUpdate(evt);
            }
        });

        searchNameBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchNameBtn1.setText("Search");
        searchNameBtn1.setPreferredSize(new java.awt.Dimension(63, 35));
        searchNameBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanel2Layout = new javax.swing.GroupLayout(searchPanel2);
        searchPanel2.setLayout(searchPanel2Layout);
        searchPanel2Layout.setHorizontalGroup(
            searchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(searchPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDesType, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchNameBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        searchPanel2Layout.setVerticalGroup(
            searchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(searchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDesType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(searchNameBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Search By Disease Name", searchPanel2);

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setText("Status: ");

        status.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        status.setText("Welcome to Sam As End Patient Admission System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(status))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        insert(id.getText(), pName.getText(), drName.getText(), desType.getText(), (String) sex.getSelectedItem());
    }//GEN-LAST:event_addActionPerformed

    private void addPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addPanelComponentShown
        clear();
    }//GEN-LAST:event_addPanelComponentShown

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
    }//GEN-LAST:event_clearActionPerformed
    ArrayList<ArrayList<String>> getArrayList() {
        return arrayList;
    }
    ArrayList<ArrayList<String>> arrayList;
    private void viewPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_viewPanelComponentShown
        try {
            ResultSet rslt = stmt.executeQuery("SELECT *\n"
                    + "FROM `paitient`\n");
            arrayList = new ArrayList<>();
            ArrayList<String> list = new ArrayList<>();
            viewTable.removeAll();
            while (rslt.next()) {
                list.clear();
                list.add("" + rslt.getInt("id"));
                list.add(rslt.getString("pName"));
                list.add(rslt.getString("sex"));
                list.add(rslt.getString("desType"));
                list.add(rslt.getString("drName"));
                arrayList.add((ArrayList<String>) list.clone());
            }
            viewTable.removeAll();
            viewTable.setModel(new AbstractTableModel() {
                ArrayList<ArrayList<String>> x = getArrayList();

                @Override
                public int getRowCount() {
                    try {
                        return x.size();
                    } catch (Exception e) {
                        return 0;
                    }
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    return x.get(rowIndex).get(columnIndex);
                }

                @Override
                public String getColumnName(int column) {
                    final String[] col = {"ID", "Patient Name", "Sex", "Disease Name", "Dr. Name"};
                    return col[column];
                }
            });
        } catch (SQLException ex) {
            displayStatus(ex.getMessage(), Color.RED);
        }
    }//GEN-LAST:event_viewPanelComponentShown

    private void updatePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updatePanelComponentShown
        lastIndex = -1;
        try {
            ResultSet rslt = stmt.executeQuery("SELECT *\n"
                    + "FROM `paitient`\n");
            arrayList = new ArrayList<>();
            ArrayList<String> list = new ArrayList<>();
            viewTable.removeAll();
            while (rslt.next()) {
                list.clear();
                list.add("" + rslt.getInt("id"));
                list.add(rslt.getString("pName"));
                list.add(rslt.getString("sex"));
                list.add(rslt.getString("desType"));
                list.add(rslt.getString("drName"));
                arrayList.add((ArrayList<String>) list.clone());
            }
            updateList.setModel(new AbstractListModel() {
                ArrayList<ArrayList<String>> x = getArrayList();

                @Override
                public int getSize() {
                    return x.size();
                }

                @Override
                public Object getElementAt(int index) {
                    ArrayList<String> list = x.get(index);
                    return "" + list.get(0) + ": " + list.get(1) + " [" + list.get(2) + "]";
                }
            });
        } catch (SQLException ex) {
            displayStatus(ex.getMessage(), Color.RED);
        }

    }//GEN-LAST:event_updatePanelComponentShown
    int lastIndex = -1;

    private void updateListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_updateListValueChanged
        int index = updateList.getSelectedIndex();
        ArrayList<ArrayList<String>> list = getArrayList();
        if (index == -1) {
            clear();
        } else if (lastIndex == index) {
        } else {
            ArrayList<String> get = list.get(index);
            updateId.setText(get.get(0));
            updatepName.setText(get.get(1));
            if ("M".equalsIgnoreCase("" + get.get(2))) {
                updateSex.setSelectedIndex(0);
            } else if ("F".equalsIgnoreCase("" + get.get(2))) {
                updateSex.setSelectedIndex(1);
            }
            updateDesType.setText(get.get(3));
            updateDrName.setText(get.get(4));
        }
        lastIndex = index;
    }//GEN-LAST:event_updateListValueChanged

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            if (updateList.getSelectedIndex() == -1) {
                throw new Exception("Select from the list first");
            }
            JTextField[] ses = {
                updatepName,
                updateDrName,
                updateDesType
            };
            for (JTextField jTextField : ses) {
                if (jTextField.getText().length() < 3) {
                    throw new Exception("Name too short(must be > 3)!!!");
                }
            }
            updatePreparedStatement.setInt(1, Integer.parseInt(updateId.getText()));
            updatePreparedStatement.setString(2, updatepName.getText());
            updatePreparedStatement.setString(3, "" + ((String) updateSex.getSelectedItem()).charAt(0));
            updatePreparedStatement.setString(4, updateDesType.getText());
            updatePreparedStatement.setString(5, updateDrName.getText());
            updatePreparedStatement.setInt(6, Integer.parseInt(getArrayList().get(updateList.getSelectedIndex()).get(0)));
            updatePreparedStatement.execute();
            clear();
            updatePanelComponentShown(null);
            displayStatus("Successfully updated", Color.GREEN);
        } catch (Exception ex) {
            displayStatus(ex.getMessage(), Color.RED);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deletePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deletePanelComponentShown
        try {
            ResultSet rslt = stmt.executeQuery("SELECT *\n"
                    + "FROM `paitient`\n");
            arrayList = new ArrayList<>();
            ArrayList<String> list = new ArrayList<>();
            while (rslt.next()) {
                list.clear();
                list.add("" + rslt.getInt("id"));
                list.add(rslt.getString("pName"));
                list.add(rslt.getString("sex"));
                list.add(rslt.getString("desType"));
                list.add(rslt.getString("drName"));
                arrayList.add((ArrayList<String>) list.clone());
            }
            deleteList.setModel(new AbstractListModel() {
                ArrayList<ArrayList<String>> x = getArrayList();
                @Override
                public int getSize() {
                    return x.size();
                }
                @Override
                public Object getElementAt(int index) {
                    ArrayList<String> list = x.get(index);
                    return "" + list.get(0) + ": " + list.get(1) + " [" + list.get(2) + "]";
                }
            });
            
        } catch (SQLException ex) {
            displayStatus(ex.getMessage(), Color.RED);
        }

    }//GEN-LAST:event_deletePanelComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (deleteList.getSelectedIndex() == -1) {
                throw new Exception("Select from the list first");
            }
            int showConfirmDialog = JOptionPane.showConfirmDialog(this,
                                            "Are you sure?\n\n", "DELETE",
                                            JOptionPane.OK_CANCEL_OPTION,
                                            JOptionPane.QUESTION_MESSAGE);
            if(showConfirmDialog == JOptionPane.CANCEL_OPTION ||
                    showConfirmDialog == JOptionPane.CLOSED_OPTION) {
                return;
            }
            int d = Integer.parseInt(getArrayList().get(deleteList.getSelectedIndex()).get(0));
            deletePreparedStatement.setInt(1, d);
            deletePreparedStatement.execute();
            deletePanelComponentShown(null);
            displayStatus("Successfully deleted", Color.GREEN);
        } catch (Exception e) {
            displayStatus(e.getMessage(), Color.RED);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_searchPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPanel1ComponentShown

    private void searchNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtnActionPerformed
        search("SELECT *\n" + "FROM `paitient` WHERE `desType` LIKE '%"+searchName.getText()+"%'\n");
    }//GEN-LAST:event_searchNameBtnActionPerformed

    private void searchNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchNameCaretUpdate
        search("SELECT *\n" + "FROM `paitient` WHERE `desType` LIKE '%"+searchName.getText()+"%'\n");
    }//GEN-LAST:event_searchNameCaretUpdate

    private void searchDesTypeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchDesTypeCaretUpdate
        search("SELECT *\n" + "FROM `paitient` WHERE `desType` LIKE '%"+searchDesType.getText()+"%'\n");
    }//GEN-LAST:event_searchDesTypeCaretUpdate

    private void searchNameBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtn1ActionPerformed
        search("SELECT *\n" + "FROM `paitient` WHERE `desType` LIKE '%"+searchDesType.getText()+"%'\n");
    }//GEN-LAST:event_searchNameBtn1ActionPerformed

    private void searchPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_searchPanel2ComponentShown
        searchDesType.setText("");
    }//GEN-LAST:event_searchPanel2ComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton clear;
    private javax.swing.JList deleteList;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JTextField desType;
    private javax.swing.JTextField drName;
    private javax.swing.JTextField id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel idLable;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField searchDesType;
    private javax.swing.JTable searchDiseaseNameTable;
    private javax.swing.JTextField searchName;
    private javax.swing.JButton searchNameBtn;
    private javax.swing.JButton searchNameBtn1;
    private javax.swing.JPanel searchPanel1;
    private javax.swing.JPanel searchPanel2;
    private javax.swing.JTable searchTable;
    private javax.swing.JComboBox sex;
    private javax.swing.JLabel status;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField updateDesType;
    private javax.swing.JTextField updateDrName;
    private javax.swing.JTextField updateId;
    private javax.swing.JList updateList;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JComboBox updateSex;
    private javax.swing.JTextField updatepName;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables

    void insert(String id, String pName, String drName, String desType, String sex) {
        try {
            String[] ses = {
                pName,
                drName,
                desType
            };
            for (String string : ses) {
                if (pName.length() < 3) {
                    throw new Exception("Name too short(must be > 3)!!!");
                }
            }
            insert.setInt(1, Integer.parseInt(id));
            insert.setString(2, pName);
            insert.setString(3, "" + sex.charAt(0));
            insert.setString(5, drName);
            insert.setString(4, desType);
        } catch (Exception ex) {
            displayStatus(ex.getMessage(), Color.RED);
            return;
        }
        try {
            insert.execute();
        } catch (SQLException ex) {
            displayStatus(ex.getMessage(), Color.RED);
            return;
        }
        clear();
        displayStatus("Successfully inserted", Color.GREEN);
    }

    private void displayStatus(String string, Color color) {
        if(color == Color.RED) {
            Start.play(Start.SOUND_ERROR);
        } else if(color == Color.GREEN) {
            Start.play(Start.SOUND_GOOD);
        }
        status.setForeground(color);
        status.setText(string);
    }

    private void clear() {
        JTextField[] jt = {
            id,
            pName,
            drName,
            desType,
            updateId,
            updateDesType,
            updateDrName,
            updatepName
        };
        for (JTextField jTextField : jt) {
            jTextField.setText("");
        }
    }

    private void search(String sql) {
        String text = searchDesType.getText();
        try {
            ResultSet rslt = stmt.executeQuery(sql);
            arrayList = new ArrayList<>();
            ArrayList<String> list = new ArrayList<>();
            searchDiseaseNameTable.removeAll();
            while (rslt.next()) {
                list.clear();
                list.add("" + rslt.getInt("id"));
                list.add(rslt.getString("pName"));
                list.add(rslt.getString("sex"));
                list.add(rslt.getString("desType"));
                list.add(rslt.getString("drName"));
                arrayList.add((ArrayList<String>) list.clone());
            }
            searchDiseaseNameTable.removeAll();
            searchDiseaseNameTable.setModel(new AbstractTableModel() {
                ArrayList<ArrayList<String>> x = getArrayList();

                @Override
                public int getRowCount() {
                    try {
                        return x.size();
                    } catch (Exception e) {
                        return 0;
                    }
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    return x.get(rowIndex).get(columnIndex);
                }

                @Override
                public String getColumnName(int column) {
                    final String[] col = {"ID", "Patient Name", "Sex", "Disease Name", "Dr. Name"};
                    return col[column];
                }
            });
        } catch (SQLException ex) {
            displayStatus(ex.getMessage(), Color.RED);
        }
    }
}
